### ISSUE TITLE
openAI key/API problems

### ISSUE THREAD

**Issue by joshuachris2001** [atisharma/llama_farm#13]
I have set the openai_api_key and I get:
`AuthenticationError: Incorrect API key provided: n/a. You can find your API key at https://platform.openai.com/account/api-keys.`
I hardcode the key in place of N/A in the defaults and I get:
`InvalidRequestError: Unrecognized request arguments supplied: openai_api_base, openai_api_key`

are there problems with the implementation of the API?

**Comment by atisharma** [comment]
Thanks for reporting this.

It should be 
```toml
api_key = "sk-XXXXX...."
api_base = "https://api.openai.com/v1"
```
I've updated the example config.
